# Generated by Django 5.2.1 on 2025-09-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_todolist_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
